backend:
  name: git-gateway
  branch: main # Branch to update

# These lines should be adjusted according to your deployment
site_url: https://digimaatwerk.nl
display_url: https://digimaatwerk.nl
logo_url: https://digimaatwerk.nl/logo.png

# Media and public folders
media_folder: "public/uploads" # Media will be stored in the repo under public/uploads
public_folder: "/uploads" # The src attribute for uploaded media

# Enables the editorial workflow - allows for draft, review, etc.
publish_mode: editorial_workflow

# Localization configuration
locale: 'nl'
i18n:
  structure: multiple_folders
  locales: [nl, en]
  default_locale: nl

# Collections
collections:
  - name: "case-studies"
    label: "Case Studies"
    folder: "public/content/case-studies"
    create: true
    slug: "{{slug}}"
    i18n: true
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Featured Image", name: "featured_image", widget: "image", i18n: true}
      - {label: "Category", name: "category", widget: "select", options: ["AI & Chatbots", "Automation", "Web Development", "Combined Solution"], i18n: true}
      - {label: "Client", name: "client", widget: "string", i18n: true}
      - {label: "Industry", name: "industry", widget: "string", i18n: true}
      - {label: "Publish Date", name: "date", widget: "datetime", i18n: true}
      - {label: "Description", name: "description", widget: "text", i18n: true}
      - {label: "Challenge", name: "challenge", widget: "text", i18n: true}
      - {label: "Solution", name: "solution", widget: "text", i18n: true}
      - {label: "Result", name: "result", widget: "text", i18n: true}
      - label: "Metrics"
        name: "metrics"
        widget: "list"
        i18n: true
        fields:
          - {label: "Label", name: "label", widget: "string", i18n: true}
          - {label: "Value", name: "value", widget: "string", i18n: true}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, i18n: true}
      - {label: "Body", name: "body", widget: "markdown", i18n: true}

  - name: "blog"
    label: "Blog"
    folder: "public/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    i18n: true
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Featured Image", name: "featured_image", widget: "image", i18n: true}
      - {label: "Author", name: "author", widget: "string", i18n: true}
      - {label: "Publish Date", name: "date", widget: "datetime", i18n: true}
      - {label: "Categories", name: "categories", widget: "list", i18n: true}
      - {label: "Tags", name: "tags", widget: "list", i18n: true}
      - {label: "Excerpt", name: "excerpt", widget: "text", i18n: true}
      - {label: "Body", name: "body", widget: "markdown", i18n: true}

  - name: "services"
    label: "Services"
    folder: "public/content/services"
    create: true
    slug: "{{slug}}"
    i18n: true
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Service Icon", name: "icon", widget: "string", i18n: true, hint: "Icon name from the library (e.g., ai-bot, automation, web)"}
      - {label: "Short Description", name: "short_description", widget: "text", i18n: true}
      - {label: "Featured Image", name: "featured_image", widget: "image", i18n: true}
      - {label: "Order", name: "order", widget: "number", default: 1, i18n: false}
      - label: "Features"
        name: "features"
        widget: "list"
        i18n: true
        fields:
          - {label: "Feature Name", name: "name", widget: "string", i18n: true}
          - {label: "Feature Description", name: "description", widget: "text", i18n: true}
      - label: "Tech Stack"
        name: "tech_stack"
        widget: "list"
        i18n: true
        fields:
          - {label: "Technology Name", name: "name", widget: "string", i18n: true}
          - {label: "Description", name: "description", widget: "text", i18n: true}
      - {label: "Body", name: "body", widget: "markdown", i18n: true}