backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: "public/uploads"
public_folder: "/uploads"
publish_mode: editorial_workflow

# Custom CMS bevindt zich op /admin/dashboard.html
# Dit bestand is alleen voor NetlifyCMS configuratie

collections:
  - name: "case-studies"
    label: "Case Studies"
    folder: "public/content/case-studies"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    i18n:
      structure: multiple_files
      locales: [nl, en]
    fields:
      - {label: "Slug", name: "slug", widget: "string", i18n: "duplicate"}
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Featured Image", name: "featured_image", widget: "image", i18n: "duplicate"}
      - {label: "Category", name: "category", widget: "select", options: ["AI & Chatbots", "Automatisering", "Webontwikkeling"], i18n: true, default: "Webontwikkeling"}
      - {label: "Client", name: "client", widget: "string", i18n: true}
      - {label: "Industry", name: "industry", widget: "string", i18n: true}
      - {label: "Date", name: "date", widget: "datetime", i18n: "duplicate"}
      - {label: "Description", name: "description", widget: "text", i18n: true}
      - {label: "Challenge", name: "challenge", widget: "text", i18n: true}
      - {label: "Solution", name: "solution", widget: "text", i18n: true}
      - {label: "Result", name: "result", widget: "text", i18n: true}
      - label: "Metrics"
        name: "metrics"
        widget: "list"
        i18n: true
        fields:
          - {label: "Label", name: "label", widget: "string"}
          - {label: "Value", name: "value", widget: "string"}
      - {label: "Live URL", name: "live_url", widget: "string", required: false, i18n: "duplicate"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, i18n: "duplicate"}
      - {label: "Content", name: "body", widget: "markdown", i18n: true}

  - name: "blog"
    label: "Blog Posts"
    folder: "public/content/blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    i18n:
      structure: multiple_files
      locales: [nl, en]
    fields:
      - {label: "Slug", name: "slug", widget: "string", i18n: "duplicate"}
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Featured Image", name: "featured_image", widget: "image", i18n: "duplicate"}
      - {label: "Author", name: "author", widget: "string", i18n: "duplicate"}
      - {label: "Date", name: "date", widget: "datetime", i18n: "duplicate"}
      - {label: "Categories", name: "categories", widget: "list", i18n: true}
      - {label: "Tags", name: "tags", widget: "list", i18n: true}
      - {label: "Excerpt", name: "excerpt", widget: "text", i18n: true}
      - {label: "Content", name: "body", widget: "markdown", i18n: true}

  - name: "services"
    label: "Services"
    folder: "public/content/services"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    i18n:
      structure: multiple_files
      locales: [nl, en]
    fields:
      - {label: "Slug", name: "slug", widget: "string", i18n: "duplicate"}
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Icon", name: "icon", widget: "string", i18n: "duplicate"}
      - {label: "Short Description", name: "short_description", widget: "text", i18n: true}
      - {label: "Featured Image", name: "featured_image", widget: "image", i18n: "duplicate"}
      - {label: "Order", name: "order", widget: "number", i18n: "duplicate"}
      - label: "Features"
        name: "features"
        widget: "list"
        i18n: true
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
      - label: "Tech Stack"
        name: "tech_stack"
        widget: "list"
        i18n: true
        fields:
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
      - {label: "Content", name: "body", widget: "markdown", i18n: true}